### PR TITLE
Avoid hallucination by letting GPT confirm the answer and give answer…

### PR DESCRIPTION
**Pull request by echo-cool**
… ranges to GPT.

Answer accuracy: 0.43 -> 0.6 -> 0.66 on min unit size.

### CODE REVIEW

**Comment by justinchiu** [comment]
looks good. what is the "avoid hallucination" part that comes before answer range?

**Comment by justinchiu** [comment]
oh can we also add verification evaluation measures to the reported results.

can we add an experiment where we loop over the districts, sample a correct page (none if there is none) and incorrect page, get  the answers + explanations from GPT, then evaluate the verification step.

Recall = num_predicted_positive_correct / num_true_positive
Precision = num_predicted_positive_correct / num_predicted_positive
F1 = 2 * (prec * rec) / (prec + rec)
[wiki source](https://en.wikipedia.org/wiki/Precision_and_recall)

ideally sample the positive + negative pages ahead of time so that we can reproduce evaluation

**Comment by echo-cool** [comment]
> looks good. what is the "avoid hallucination" part that comes before answer range?

I was basically adding "return NO_ANSWER if there's no good answer." to tournament reduce and "If the answer is not in the text, you should also return "N", DO NOT fake an answer or make assumptions." to answer confirm.

**Comment by echo-cool** [comment]
I also found GPT sometimes think "min unit size" and "min lot size" are synonyms. So in 3297a38af436aa0576b3f6ca4162c4043e7a4fbc, I add this part to the answer confirm process:

```
However, "{{term}}" is different than {{not_synonyms}}, they are not synonyms. If you see any of these "not synonym words" in the text, the answer is incorrect.
```

**Comment by echo-cool** [comment]
> oh can we also add verification evaluation measures to the reported results.
> 
> can we add an experiment where we loop over the districts, sample a correct page (none if there is none) and incorrect page, get the answers + explanations from GPT, then evaluate the verification step. this will allow us to get a more fine-grained view of how we are doing in verification -- at the start we probably have high recall and low precision. it would be nice to see how that has changed
> 
> ```
> Recall = num_predicted_positive_correct / num_true_positive
> Precision = num_predicted_positive_correct / num_predicted_positive
> F1 = 2 * (prec * rec) / (prec + rec)
> ```
> 
> [wiki source](https://en.wikipedia.org/wiki/Precision_and_recall)
> 
> ideally sample the positive + negative pages ahead of time so that we can reproduce evaluation

Add in 072333b4ae71a1d511184cf3f7f257a7ca04867f

**Comment by echo-cool** [comment]
@Nathaniel-Nirmal Hi Nathaniel, I am not sure which part of the project you are currently working on. If you have time, can you also help me review the Recall, Precision, F1 implementation? Also can you try adding "District - answer ordering: We saw in our error analysis that sometimes the district came after the answer, but was mistakenly associated with that answer" prompts to the project and collect the corresponding evaluation metric after adding this prompt?

**Pull request merged**
